begin;

create table if not exists public.meals (
  id integer generated by default as identity (start with 10000) primary key,
  household_id uuid references public.households(id) on delete cascade,
  name text not null check (char_length(name) between 2 and 100),
  description text not null default '',
  collection text not null default 'main_fasting'
    check (collection in ('main_fasting', 'breakfast', 'optional_snack', 'family', 'custom')),
  category text not null,
  ingredients jsonb not null default '[]'::jsonb
    check (jsonb_typeof(ingredients) = 'array'),
  instructions jsonb not null default '[]'::jsonb
    check (jsonb_typeof(instructions) = 'array'),
  cooking_time integer not null check (cooking_time between 1 and 360),
  difficulty text not null default 'Fácil'
    check (difficulty in ('Fácil', 'Media')),
  tags text[] not null default '{}',
  protein boolean not null default false,
  healthy boolean not null default false,
  air_fryer boolean not null default false,
  notes text not null default '',
  is_system boolean generated always as (household_id is null) stored,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.household_meal_preferences (
  household_id uuid not null references public.households(id) on delete cascade,
  meal_id integer not null references public.meals(id) on delete cascade,
  is_favorite boolean not null default false,
  is_hidden boolean not null default false,
  updated_at timestamptz not null default now(),
  primary key (household_id, meal_id)
);

create index if not exists meals_household_id_idx
  on public.meals(household_id);
create index if not exists meals_collection_category_idx
  on public.meals(collection, category);
create index if not exists household_meal_preferences_meal_idx
  on public.household_meal_preferences(meal_id);

alter table public.meals enable row level security;
alter table public.household_meal_preferences enable row level security;

drop policy if exists "Members can read meal catalog" on public.meals;
create policy "Members can read meal catalog"
on public.meals for select to authenticated
using (
  household_id is null
  or exists (
    select 1 from public.household_members hm
    where hm.household_id = meals.household_id
      and hm.user_id = auth.uid()
  )
);

drop policy if exists "Members can create household meals" on public.meals;
create policy "Members can create household meals"
on public.meals for insert to authenticated
with check (
  household_id is not null
  and created_by = auth.uid()
  and exists (
    select 1 from public.household_members hm
    where hm.household_id = meals.household_id
      and hm.user_id = auth.uid()
  )
);

drop policy if exists "Members can update household meals" on public.meals;
create policy "Members can update household meals"
on public.meals for update to authenticated
using (
  household_id is not null
  and exists (
    select 1 from public.household_members hm
    where hm.household_id = meals.household_id
      and hm.user_id = auth.uid()
  )
)
with check (
  household_id is not null
  and exists (
    select 1 from public.household_members hm
    where hm.household_id = meals.household_id
      and hm.user_id = auth.uid()
  )
);

drop policy if exists "Members can delete household meals" on public.meals;
create policy "Members can delete household meals"
on public.meals for delete to authenticated
using (
  household_id is not null
  and exists (
    select 1 from public.household_members hm
    where hm.household_id = meals.household_id
      and hm.user_id = auth.uid()
  )
);

drop policy if exists "Members can read meal preferences" on public.household_meal_preferences;
create policy "Members can read meal preferences"
on public.household_meal_preferences for select to authenticated
using (
  exists (
    select 1 from public.household_members hm
    where hm.household_id = household_meal_preferences.household_id
      and hm.user_id = auth.uid()
  )
);

drop policy if exists "Members can create meal preferences" on public.household_meal_preferences;
create policy "Members can create meal preferences"
on public.household_meal_preferences for insert to authenticated
with check (
  exists (
    select 1 from public.household_members hm
    where hm.household_id = household_meal_preferences.household_id
      and hm.user_id = auth.uid()
  )
);

drop policy if exists "Members can update meal preferences" on public.household_meal_preferences;
create policy "Members can update meal preferences"
on public.household_meal_preferences for update to authenticated
using (
  exists (
    select 1 from public.household_members hm
    where hm.household_id = household_meal_preferences.household_id
      and hm.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.household_members hm
    where hm.household_id = household_meal_preferences.household_id
      and hm.user_id = auth.uid()
  )
);

drop policy if exists "Members can delete meal preferences" on public.household_meal_preferences;
create policy "Members can delete meal preferences"
on public.household_meal_preferences for delete to authenticated
using (
  exists (
    select 1 from public.household_members hm
    where hm.household_id = household_meal_preferences.household_id
      and hm.user_id = auth.uid()
  )
);

commit;
