begin;

insert into public.meals (
  id, name, description, collection, category, ingredients, instructions,
  cooking_time, difficulty, tags, protein, healthy, air_fryer, notes
)
values
(
  1,
  'Pollo al horno con patatas',
  'Pollo al horno con patatas, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pollo',
  '[{"name":"Pechuga de pollo","quantity":"300 g"},{"name":"Patatas","quantity":"400 g"},{"name":"Aceite de oliva","quantity":"1 cucharada"},{"name":"Sal","quantity":"Al gusto"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona patatas.","Coloca pechuga de pollo y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que pechuga de pollo alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  40,
  'Fácil',
  array['Cocina casera', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  2,
  'Pollo al limón',
  'Pollo al limón, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pollo',
  '[{"name":"Pechuga de pollo","quantity":"300 g"},{"name":"Limón","quantity":"1 unidad"},{"name":"Ajo","quantity":"1 diente"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Prepara ajo y sazona pechuga de pollo.","Calienta bien una sartén o plancha con el aceite y cocina pechuga de pollo sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  25,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  3,
  'Fajitas de pollo',
  'Fajitas de pollo, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Wraps',
  '[{"name":"Pechuga de pollo","quantity":"300 g"},{"name":"Tortitas de trigo","quantity":"4 unidades"},{"name":"Lechuga","quantity":"0,5 unidades"},{"name":"Zanahoria","quantity":"1 unidad"}]'::jsonb,
  '["Prepara tortitas de trigo y lechuga y sazona pechuga de pollo.","Calienta bien una sartén o plancha con el aceite y cocina pechuga de pollo sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  20,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  4,
  'Arroz con pollo',
  'Arroz con pollo, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Arroz',
  '[{"name":"Pechuga de pollo","quantity":"300 g"},{"name":"Arroz","quantity":"160 g"},{"name":"Caldo de pollo","quantity":"400 ml"},{"name":"Zanahoria","quantity":"1 unidad"}]'::jsonb,
  '["Trocea y sazona pechuga de pollo; prepara también arroz y zanahoria.","Rehoga la proteína y las verduras con el aceite hasta que empiecen a dorarse.","Incorpora el arroz, mezcla durante un minuto y añade el caldo caliente.","Cuece sin remover en exceso hasta que el arroz esté en su punto y déjalo reposar 5 minutos."]'::jsonb,
  35,
  'Fácil',
  array['Cocina casera', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  5,
  'Pavo a la plancha con patatas',
  'Pavo a la plancha con patatas, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pollo',
  '[{"name":"Filetes de pavo","quantity":"300 g"},{"name":"Patatas","quantity":"400 g"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Prepara patatas y sazona filetes de pavo.","Calienta bien una sartén o plancha con el aceite y cocina filetes de pavo sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  25,
  'Fácil',
  array['Rápido', 'Airfryer', 'Equilibrado']::text[],
  true,
  true,
  true,
  ''
),
(
  6,
  'Hamburguesa casera con patatas',
  'Hamburguesa casera con patatas, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Caprichos',
  '[{"name":"Carne picada de ternera","quantity":"300 g"},{"name":"Pan de hamburguesa","quantity":"2 unidades"},{"name":"Lechuga","quantity":"0,5 unidades"},{"name":"Patatas","quantity":"400 g"}]'::jsonb,
  '["Prepara pan de hamburguesa y lechuga y sazona carne picada de ternera.","Calienta bien una sartén o plancha con el aceite y cocina carne picada de ternera sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera', 'Airfryer', 'Capricho']::text[],
  true,
  false,
  true,
  ''
),
(
  7,
  'Filete fino de ternera con arroz',
  'Filete fino de ternera con arroz, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Carne',
  '[{"name":"Filetes finos de ternera","quantity":"2 unidades"},{"name":"Arroz","quantity":"160 g"},{"name":"Aceite de oliva","quantity":"1 cucharadita"}]'::jsonb,
  '["Trocea y sazona filetes finos de ternera; prepara también arroz.","Rehoga la proteína y las verduras con el aceite hasta que empiecen a dorarse.","Incorpora el arroz, mezcla durante un minuto y añade el caldo caliente.","Cuece sin remover en exceso hasta que el arroz esté en su punto y déjalo reposar 5 minutos."]'::jsonb,
  20,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  8,
  'Berenjenas rellenas de carne',
  'Berenjenas rellenas de carne, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Carne',
  '[{"name":"Berenjenas","quantity":"2 unidades"},{"name":"Carne picada de ternera","quantity":"300 g"},{"name":"Zanahoria","quantity":"1 unidad"},{"name":"Queso rallado","quantity":"80 g"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona carne picada de ternera y zanahoria.","Coloca berenjenas y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que berenjenas alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  45,
  'Media',
  array['Cocina casera', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  9,
  'Berenjenas rellenas de pollo',
  'Berenjenas rellenas de pollo, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pollo',
  '[{"name":"Berenjenas","quantity":"2 unidades"},{"name":"Pechuga de pollo","quantity":"300 g"},{"name":"Zanahoria","quantity":"1 unidad"},{"name":"Queso rallado","quantity":"80 g"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona pechuga de pollo y zanahoria.","Coloca berenjenas y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que berenjenas alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  45,
  'Media',
  array['Cocina casera', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  10,
  'Salmón a la plancha con patatas',
  'Salmón a la plancha con patatas, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pescado',
  '[{"name":"Lomos de salmón","quantity":"2 unidades"},{"name":"Patatas","quantity":"400 g"},{"name":"Aceite de oliva","quantity":"1 cucharadita"}]'::jsonb,
  '["Prepara la guarnición y sazona patatas.","Calienta bien una sartén o plancha con el aceite y cocina patatas sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  25,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  11,
  'Atún a la plancha con ensalada',
  'Atún a la plancha con ensalada, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pescado',
  '[{"name":"Filetes de atún","quantity":"2 unidades"},{"name":"Lechuga","quantity":"0,5 unidades"},{"name":"Zanahoria","quantity":"1 unidad"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Lava, seca y corta lechuga y zanahoria.","Prepara filetes de atún y deja que se temple antes de mezclarlo si se ha cocinado.","Combina los ingredientes en un bol amplio y prepara el aliño por separado.","Aliña justo antes de servir, mezcla bien y ajusta el punto de sal."]'::jsonb,
  15,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  12,
  'Gambas a la plancha',
  'Gambas a la plancha, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pescado',
  '[{"name":"Gambas","quantity":"500 g"},{"name":"Ajo","quantity":"2 dientes"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Prepara ajo y sazona gambas.","Calienta bien una sartén o plancha con el aceite y cocina gambas sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  15,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  13,
  'Espaguetis boloñesa',
  'Espaguetis boloñesa, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pasta',
  '[{"name":"Espaguetis","quantity":"160 g"},{"name":"Carne picada de ternera","quantity":"250 g"},{"name":"Tomate frito","quantity":"200 g"},{"name":"Zanahoria","quantity":"1 unidad"}]'::jsonb,
  '["Cuece la pasta en agua con sal hasta dejarla al dente y reserva un poco del agua de cocción.","Mientras, cocina espaguetis con carne picada de ternera y tomate frito en una sartén amplia.","Añade la pasta escurrida, mezcla con la salsa y usa un poco del agua reservada si necesita quedar más jugosa.","Cocina todo junto un minuto y sirve recién hecho."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera', 'Capricho']::text[],
  true,
  false,
  false,
  ''
),
(
  14,
  'Macarrones con atún',
  'Macarrones con atún, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pasta',
  '[{"name":"Macarrones","quantity":"160 g"},{"name":"Atún al natural","quantity":"2 latas"},{"name":"Tomate frito","quantity":"200 g"}]'::jsonb,
  '["Cuece la pasta en agua con sal hasta dejarla al dente y reserva un poco del agua de cocción.","Mientras, cocina macarrones con atún al natural y tomate frito en una sartén amplia.","Añade la pasta escurrida, mezcla con la salsa y usa un poco del agua reservada si necesita quedar más jugosa.","Cocina todo junto un minuto y sirve recién hecho."]'::jsonb,
  20,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  15,
  'Tortilla francesa con pavo',
  'Tortilla francesa con pavo, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Huevos',
  '[{"name":"Huevos","quantity":"4 unidades"},{"name":"Pavo en lonchas","quantity":"100 g"},{"name":"Aceite de oliva","quantity":"1 cucharadita"}]'::jsonb,
  '["Prepara pavo en lonchas y sazona huevos.","Calienta bien una sartén o plancha con el aceite y cocina huevos sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  10,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  16,
  'Pollo a la plancha con arroz',
  'Pollo a la plancha con arroz, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pollo',
  '[{"name":"Pechuga de pollo","quantity":"300 g"},{"name":"Arroz","quantity":"160 g"},{"name":"Aceite de oliva","quantity":"1 cucharadita"}]'::jsonb,
  '["Trocea y sazona pechuga de pollo; prepara también arroz.","Rehoga la proteína y las verduras con el aceite hasta que empiecen a dorarse.","Incorpora el arroz, mezcla durante un minuto y añade el caldo caliente.","Cuece sin remover en exceso hasta que el arroz esté en su punto y déjalo reposar 5 minutos."]'::jsonb,
  20,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  17,
  'Pollo con calabacín',
  'Pollo con calabacín, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pollo',
  '[{"name":"Pechuga de pollo","quantity":"300 g"},{"name":"Calabacín","quantity":"1 unidad"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Prepara calabacín y sazona pechuga de pollo.","Calienta bien una sartén o plancha con el aceite y cocina pechuga de pollo sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  25,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  18,
  'Pollo al curry suave',
  'Pollo al curry suave, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pollo',
  '[{"name":"Pechuga de pollo","quantity":"300 g"},{"name":"Leche evaporada","quantity":"150 ml"},{"name":"Curry suave","quantity":"1 cucharadita"},{"name":"Arroz","quantity":"140 g"}]'::jsonb,
  '["Trocea y prepara pechuga de pollo, leche evaporada y arroz antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade pechuga de pollo, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  19,
  'Pollo empanado en air fryer',
  'Pollo empanado en air fryer, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pollo',
  '[{"name":"Pechuga de pollo","quantity":"300 g"},{"name":"Pan rallado","quantity":"50 g"},{"name":"Huevo","quantity":"1 unidad"}]'::jsonb,
  '["Precalienta la airfryer a 190 °C y prepara pechuga de pollo con el aliño indicado.","Coloca pechuga de pollo en una sola capa, sin amontonar, y pulveriza o reparte el aceite medido.","Cocina hasta que quede dorado, dando la vuelta o agitando la cesta a mitad del tiempo.","Comprueba que el interior esté bien cocinado y sirve con la guarnición."]'::jsonb,
  20,
  'Fácil',
  array['Rápido', 'Airfryer', 'Equilibrado']::text[],
  true,
  true,
  true,
  ''
),
(
  20,
  'Brochetas de pollo y calabacín',
  'Brochetas de pollo y calabacín, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pollo',
  '[{"name":"Pechuga de pollo","quantity":"300 g"},{"name":"Calabacín","quantity":"1 unidad"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Prepara calabacín y sazona pechuga de pollo.","Calienta bien una sartén o plancha con el aceite y cocina pechuga de pollo sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  25,
  'Fácil',
  array['Rápido', 'Airfryer', 'Equilibrado']::text[],
  true,
  true,
  true,
  ''
),
(
  21,
  'Pavo con arroz',
  'Pavo con arroz, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pollo',
  '[{"name":"Filetes de pavo","quantity":"300 g"},{"name":"Arroz","quantity":"160 g"},{"name":"Aceite de oliva","quantity":"1 cucharadita"}]'::jsonb,
  '["Trocea y sazona filetes de pavo; prepara también arroz.","Rehoga la proteína y las verduras con el aceite hasta que empiecen a dorarse.","Incorpora el arroz, mezcla durante un minuto y añade el caldo caliente.","Cuece sin remover en exceso hasta que el arroz esté en su punto y déjalo reposar 5 minutos."]'::jsonb,
  20,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  22,
  'Albóndigas de pollo',
  'Albóndigas de pollo, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pollo',
  '[{"name":"Carne picada de pollo","quantity":"350 g"},{"name":"Huevo","quantity":"1 unidad"},{"name":"Pan rallado","quantity":"30 g"},{"name":"Zanahoria","quantity":"1 unidad"}]'::jsonb,
  '["Trocea y prepara carne picada de pollo, huevo y pan rallado antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade carne picada de pollo, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  35,
  'Media',
  array['Cocina casera', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  23,
  'Ternera con patatas al horno',
  'Ternera con patatas al horno, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Carne',
  '[{"name":"Filetes finos de ternera","quantity":"2 unidades"},{"name":"Patatas","quantity":"400 g"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona patatas.","Coloca filetes finos de ternera y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que filetes finos de ternera alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  24,
  'Albóndigas de ternera',
  'Albóndigas de ternera, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Carne',
  '[{"name":"Carne picada de ternera","quantity":"350 g"},{"name":"Huevo","quantity":"1 unidad"},{"name":"Pan rallado","quantity":"30 g"},{"name":"Zanahoria","quantity":"1 unidad"}]'::jsonb,
  '["Trocea y prepara carne picada de ternera, huevo y pan rallado antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade carne picada de ternera, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  35,
  'Media',
  array['Cocina casera', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  25,
  'Ternera salteada con arroz',
  'Ternera salteada con arroz, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Carne',
  '[{"name":"Ternera en tiras finas","quantity":"300 g"},{"name":"Arroz","quantity":"160 g"},{"name":"Calabacín","quantity":"1 unidad"}]'::jsonb,
  '["Trocea y sazona ternera en tiras finas; prepara también arroz y calabacín.","Rehoga la proteína y las verduras con el aceite hasta que empiecen a dorarse.","Incorpora el arroz, mezcla durante un minuto y añade el caldo caliente.","Cuece sin remover en exceso hasta que el arroz esté en su punto y déjalo reposar 5 minutos."]'::jsonb,
  25,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  26,
  'Hamburguesa de pollo',
  'Hamburguesa de pollo, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pollo',
  '[{"name":"Carne picada de pollo","quantity":"300 g"},{"name":"Pan de hamburguesa","quantity":"2 unidades"},{"name":"Lechuga","quantity":"0,5 unidades"},{"name":"Patatas","quantity":"300 g"}]'::jsonb,
  '["Prepara pan de hamburguesa y lechuga y sazona carne picada de pollo.","Calienta bien una sartén o plancha con el aceite y cocina carne picada de pollo sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera', 'Airfryer', 'Equilibrado']::text[],
  true,
  true,
  true,
  ''
),
(
  27,
  'Salmón al horno con arroz',
  'Salmón al horno con arroz, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pescado',
  '[{"name":"Lomos de salmón","quantity":"2 unidades"},{"name":"Arroz","quantity":"160 g"},{"name":"Limón","quantity":"1 unidad"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona los acompañamientos.","Coloca arroz y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que arroz alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  25,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  28,
  'Salmón en air fryer',
  'Salmón en air fryer, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pescado',
  '[{"name":"Lomos de salmón","quantity":"2 unidades"},{"name":"Patatas","quantity":"350 g"}]'::jsonb,
  '["Precalienta la airfryer a 190 °C y prepara patatas con el aliño indicado.","Coloca patatas en una sola capa, sin amontonar, y pulveriza o reparte el aceite medido.","Cocina hasta que quede dorado, dando la vuelta o agitando la cesta a mitad del tiempo.","Comprueba que el interior esté bien cocinado y sirve con la guarnición."]'::jsonb,
  25,
  'Fácil',
  array['Rápido', 'Airfryer', 'Equilibrado']::text[],
  true,
  true,
  true,
  ''
),
(
  29,
  'Merluza rebozada en air fryer',
  'Merluza rebozada en air fryer, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pescado',
  '[{"name":"Filetes de merluza","quantity":"2 unidades"},{"name":"Huevo","quantity":"1 unidad"},{"name":"Pan rallado","quantity":"50 g"}]'::jsonb,
  '["Precalienta la airfryer a 190 °C y prepara filetes de merluza con el aliño indicado.","Coloca filetes de merluza en una sola capa, sin amontonar, y pulveriza o reparte el aceite medido.","Cocina hasta que quede dorado, dando la vuelta o agitando la cesta a mitad del tiempo.","Comprueba que el interior esté bien cocinado y sirve con la guarnición."]'::jsonb,
  18,
  'Fácil',
  array['Rápido', 'Airfryer', 'Equilibrado']::text[],
  true,
  true,
  true,
  ''
),
(
  30,
  'Merluza al horno con patatas',
  'Merluza al horno con patatas, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pescado',
  '[{"name":"Filetes de merluza","quantity":"2 unidades"},{"name":"Patatas","quantity":"400 g"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona patatas.","Coloca filetes de merluza y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que filetes de merluza alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  35,
  'Fácil',
  array['Cocina casera', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  31,
  'Revuelto de gambas',
  'Revuelto de gambas, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Huevos',
  '[{"name":"Huevos","quantity":"4 unidades"},{"name":"Gambas peladas","quantity":"250 g"},{"name":"Ajo","quantity":"1 diente"}]'::jsonb,
  '["Prepara gambas peladas y ajo y sazona huevos.","Calienta bien una sartén o plancha con el aceite y cocina huevos sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  15,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  32,
  'Arroz con gambas',
  'Arroz con gambas, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Arroz',
  '[{"name":"Arroz","quantity":"160 g"},{"name":"Gambas peladas","quantity":"300 g"},{"name":"Caldo de pescado","quantity":"400 ml"}]'::jsonb,
  '["Trocea y sazona arroz; prepara también gambas peladas.","Rehoga la proteína y las verduras con el aceite hasta que empiecen a dorarse.","Incorpora el arroz, mezcla durante un minuto y añade el caldo caliente.","Cuece sin remover en exceso hasta que el arroz esté en su punto y déjalo reposar 5 minutos."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  33,
  'Paella sencilla de marisco',
  'Paella sencilla de marisco, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Arroz',
  '[{"name":"Arroz","quantity":"160 g"},{"name":"Gambas","quantity":"250 g"},{"name":"Caldo de pescado","quantity":"450 ml"},{"name":"Calamar troceado","quantity":"150 g"}]'::jsonb,
  '["Trocea y sazona arroz; prepara también gambas y calamar troceado.","Rehoga la proteína y las verduras con el aceite hasta que empiecen a dorarse.","Incorpora el arroz, mezcla durante un minuto y añade el caldo caliente.","Cuece sin remover en exceso hasta que el arroz esté en su punto y déjalo reposar 5 minutos."]'::jsonb,
  35,
  'Media',
  array['Cocina casera', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  34,
  'Pasta con pollo',
  'Pasta con pollo, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pasta',
  '[{"name":"Pasta","quantity":"160 g"},{"name":"Pechuga de pollo","quantity":"250 g"},{"name":"Calabacín","quantity":"1 unidad"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Cuece la pasta en agua con sal hasta dejarla al dente y reserva un poco del agua de cocción.","Mientras, cocina pasta con pechuga de pollo y calabacín en una sartén amplia.","Añade la pasta escurrida, mezcla con la salsa y usa un poco del agua reservada si necesita quedar más jugosa.","Cocina todo junto un minuto y sirve recién hecho."]'::jsonb,
  25,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  35,
  'Pasta con salmón',
  'Pasta con salmón, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pasta',
  '[{"name":"Pasta","quantity":"160 g"},{"name":"Salmón","quantity":"250 g"},{"name":"Leche evaporada","quantity":"120 ml"}]'::jsonb,
  '["Cuece la pasta en agua con sal hasta dejarla al dente y reserva un poco del agua de cocción.","Mientras, cocina pasta con leche evaporada en una sartén amplia.","Añade la pasta escurrida, mezcla con la salsa y usa un poco del agua reservada si necesita quedar más jugosa.","Cocina todo junto un minuto y sirve recién hecho."]'::jsonb,
  25,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  36,
  'Pasta con gambas',
  'Pasta con gambas, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pasta',
  '[{"name":"Pasta","quantity":"160 g"},{"name":"Gambas peladas","quantity":"250 g"},{"name":"Ajo","quantity":"1 diente"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Cuece la pasta en agua con sal hasta dejarla al dente y reserva un poco del agua de cocción.","Mientras, cocina pasta con gambas peladas y ajo en una sartén amplia.","Añade la pasta escurrida, mezcla con la salsa y usa un poco del agua reservada si necesita quedar más jugosa.","Cocina todo junto un minuto y sirve recién hecho."]'::jsonb,
  20,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  37,
  'Lasaña de carne y calabacín',
  'Lasaña de carne y calabacín, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pasta',
  '[{"name":"Placas de lasaña","quantity":"6 unidades"},{"name":"Carne picada de ternera","quantity":"300 g"},{"name":"Calabacín","quantity":"1 unidad"},{"name":"Queso rallado","quantity":"60 g"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona carne picada de ternera y calabacín.","Coloca placas de lasaña y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que placas de lasaña alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  50,
  'Media',
  array['Cocina casera', 'Capricho']::text[],
  true,
  false,
  false,
  ''
),
(
  38,
  'Arroz a la cubana',
  'Arroz a la cubana, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Arroz',
  '[{"name":"Arroz","quantity":"160 g"},{"name":"Huevos","quantity":"2 unidades"},{"name":"Tomate frito","quantity":"150 g"},{"name":"Plátano","quantity":"1 unidad"}]'::jsonb,
  '["Trocea y sazona arroz; prepara también huevos y tomate frito.","Rehoga la proteína y las verduras con el aceite hasta que empiecen a dorarse.","Incorpora el arroz, mezcla durante un minuto y añade el caldo caliente.","Cuece sin remover en exceso hasta que el arroz esté en su punto y déjalo reposar 5 minutos."]'::jsonb,
  25,
  'Fácil',
  array['Rápido', 'Capricho']::text[],
  true,
  false,
  false,
  ''
),
(
  39,
  'Arroz tres delicias casero',
  'Arroz tres delicias casero, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Arroz',
  '[{"name":"Arroz","quantity":"160 g"},{"name":"Huevos","quantity":"2 unidades"},{"name":"Pavo en dados","quantity":"100 g"},{"name":"Zanahoria","quantity":"1 unidad"}]'::jsonb,
  '["Trocea y sazona arroz; prepara también huevos y pavo en dados.","Rehoga la proteína y las verduras con el aceite hasta que empiecen a dorarse.","Incorpora el arroz, mezcla durante un minuto y añade el caldo caliente.","Cuece sin remover en exceso hasta que el arroz esté en su punto y déjalo reposar 5 minutos."]'::jsonb,
  25,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  40,
  'Tortilla de patatas ligera',
  'Tortilla de patatas ligera, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Huevos',
  '[{"name":"Huevos","quantity":"5 unidades"},{"name":"Patatas","quantity":"400 g"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Prepara patatas y sazona huevos.","Calienta bien una sartén o plancha con el aceite y cocina huevos sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  30,
  'Media',
  array['Cocina casera', 'Airfryer', 'Equilibrado']::text[],
  true,
  true,
  true,
  ''
),
(
  41,
  'Huevos rellenos de atún',
  'Huevos rellenos de atún, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Huevos',
  '[{"name":"Huevos","quantity":"4 unidades"},{"name":"Atún al natural","quantity":"2 latas"},{"name":"Mayonesa ligera","quantity":"2 cucharadas"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona atún al natural y mayonesa ligera.","Coloca huevos y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que huevos alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  20,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  42,
  'Ensalada de pollo y huevo',
  'Ensalada de pollo y huevo, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Ligero',
  '[{"name":"Lechuga","quantity":"1 unidad"},{"name":"Pechuga de pollo","quantity":"250 g"},{"name":"Huevos","quantity":"2 unidades"},{"name":"Zanahoria","quantity":"1 unidad"}]'::jsonb,
  '["Lava, seca y corta pechuga de pollo y huevos.","Prepara lechuga y deja que se temple antes de mezclarlo si se ha cocinado.","Combina los ingredientes en un bol amplio y prepara el aliño por separado.","Aliña justo antes de servir, mezcla bien y ajusta el punto de sal."]'::jsonb,
  20,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  43,
  'Ensalada de atún y huevo',
  'Ensalada de atún y huevo, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Ligero',
  '[{"name":"Lechuga","quantity":"1 unidad"},{"name":"Atún al natural","quantity":"2 latas"},{"name":"Huevos","quantity":"2 unidades"},{"name":"Zanahoria","quantity":"1 unidad"}]'::jsonb,
  '["Lava, seca y corta atún al natural y huevos.","Prepara lechuga y deja que se temple antes de mezclarlo si se ha cocinado.","Combina los ingredientes en un bol amplio y prepara el aliño por separado.","Aliña justo antes de servir, mezcla bien y ajusta el punto de sal."]'::jsonb,
  15,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  44,
  'Calabacines rellenos de pollo',
  'Calabacines rellenos de pollo, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pollo',
  '[{"name":"Calabacines","quantity":"2 unidades"},{"name":"Pechuga de pollo","quantity":"300 g"},{"name":"Zanahoria","quantity":"1 unidad"},{"name":"Queso rallado","quantity":"60 g"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona pechuga de pollo y zanahoria.","Coloca calabacines y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que calabacines alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  40,
  'Media',
  array['Cocina casera', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  45,
  'Calabacines rellenos de atún',
  'Calabacines rellenos de atún, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pescado',
  '[{"name":"Calabacines","quantity":"2 unidades"},{"name":"Atún al natural","quantity":"2 latas"},{"name":"Huevos","quantity":"2 unidades"},{"name":"Queso rallado","quantity":"60 g"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona atún al natural y huevos.","Coloca calabacines y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que calabacines alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  35,
  'Media',
  array['Cocina casera', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  46,
  'Pizza casera de pollo',
  'Pizza casera de pollo, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Caprichos',
  '[{"name":"Base de pizza fina","quantity":"1 unidad"},{"name":"Pechuga de pollo","quantity":"200 g"},{"name":"Queso rallado","quantity":"80 g"},{"name":"Tomate frito","quantity":"100 g"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona pechuga de pollo y queso rallado.","Coloca base de pizza fina y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que base de pizza fina alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  25,
  'Fácil',
  array['Rápido', 'Capricho']::text[],
  true,
  false,
  false,
  ''
),
(
  47,
  'Pizza casera de atún',
  'Pizza casera de atún, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Caprichos',
  '[{"name":"Base de pizza fina","quantity":"1 unidad"},{"name":"Atún al natural","quantity":"2 latas"},{"name":"Queso rallado","quantity":"80 g"},{"name":"Tomate frito","quantity":"100 g"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona atún al natural y queso rallado.","Coloca base de pizza fina y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que base de pizza fina alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  20,
  'Fácil',
  array['Rápido', 'Capricho']::text[],
  true,
  false,
  false,
  ''
),
(
  48,
  'Kebab casero de pollo',
  'Kebab casero de pollo, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Wraps',
  '[{"name":"Pechuga de pollo","quantity":"300 g"},{"name":"Pan de pita","quantity":"2 unidades"},{"name":"Lechuga","quantity":"0,5 unidades"},{"name":"Salsa de yogur ligera","quantity":"2 cucharadas"}]'::jsonb,
  '["Prepara pan de pita y lechuga y sazona pechuga de pollo.","Calienta bien una sartén o plancha con el aceite y cocina pechuga de pollo sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  25,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  49,
  'Wrap de atún y huevo',
  'Wrap de atún y huevo, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Wraps',
  '[{"name":"Tortitas de trigo","quantity":"4 unidades"},{"name":"Atún al natural","quantity":"2 latas"},{"name":"Huevos","quantity":"2 unidades"},{"name":"Lechuga","quantity":"0,5 unidades"}]'::jsonb,
  '["Lava, seca y corta atún al natural y huevos.","Prepara tortitas de trigo y deja que se temple antes de mezclarlo si se ha cocinado.","Combina los ingredientes en un bol amplio y prepara el aliño por separado.","Aliña justo antes de servir, mezcla bien y ajusta el punto de sal."]'::jsonb,
  20,
  'Fácil',
  array['Rápido', 'Equilibrado']::text[],
  true,
  true,
  false,
  ''
),
(
  50,
  'Boquerones fritos con ensalada',
  'Boquerones fritos con ensalada, preparado como comida principal completa para dos personas.',
  'main_fasting',
  'Pescado',
  '[{"name":"Boquerones limpios","quantity":"400 g"},{"name":"Harina","quantity":"50 g"},{"name":"Lechuga","quantity":"0,5 unidades"},{"name":"Zanahoria","quantity":"1 unidad"}]'::jsonb,
  '["Lava, seca y corta harina y lechuga.","Prepara boquerones limpios y deja que se temple antes de mezclarlo si se ha cocinado.","Combina los ingredientes en un bol amplio y prepara el aliño por separado.","Aliña justo antes de servir, mezcla bien y ajusta el punto de sal."]'::jsonb,
  25,
  'Media',
  array['Rápido', 'Capricho']::text[],
  true,
  false,
  false,
  'Ocasional.'
),
(
  51,
  'Lentejas guisadas con verduras y huevo',
  'Lentejas guisadas con verduras y huevo: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Huevos',
  '[{"name":"Lentejas cocidas","quantity":"400 g"},{"name":"Huevos","quantity":"2"},{"name":"Zanahoria","quantity":"1"},{"name":"Calabacín","quantity":"1"},{"name":"Caldo de verduras","quantity":"500 ml"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Trocea y prepara lentejas cocidas, huevos y zanahoria antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade lentejas cocidas, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  45,
  'Media',
  array['Cocina casera', 'Legumbres', 'Saciantes']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  52,
  'Garbanzos con espinacas y huevo',
  'Garbanzos con espinacas y huevo: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Huevos',
  '[{"name":"Garbanzos cocidos","quantity":"400 g"},{"name":"Espinacas","quantity":"250 g"},{"name":"Huevos","quantity":"2"},{"name":"Ajo","quantity":"2 dientes"},{"name":"Pimentón","quantity":"1 cucharadita"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Trocea y prepara garbanzos cocidos, espinacas y huevos antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade garbanzos cocidos, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  30,
  'Media',
  array['Cocina casera', 'Legumbres']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  53,
  'Ensalada templada de garbanzos y atún',
  'Ensalada templada de garbanzos y atún: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Ligero',
  '[{"name":"Garbanzos cocidos","quantity":"350 g"},{"name":"Atún al natural","quantity":"2 latas"},{"name":"Huevos","quantity":"2"},{"name":"Zanahoria","quantity":"1"},{"name":"Lechuga","quantity":"150 g"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Lava, seca y corta atún al natural y huevos.","Prepara garbanzos cocidos y deja que se temple antes de mezclarlo si se ha cocinado.","Combina los ingredientes en un bol amplio y prepara el aliño por separado.","Aliña justo antes de servir, mezcla bien y ajusta el punto de sal."]'::jsonb,
  20,
  'Fácil',
  array['Rápido', 'Legumbres', 'Rápido']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  54,
  'Judías blancas con merluza',
  'Judías blancas con merluza: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pescado',
  '[{"name":"Judías blancas cocidas","quantity":"400 g"},{"name":"Merluza","quantity":"300 g"},{"name":"Zanahoria","quantity":"1"},{"name":"Caldo de pescado","quantity":"400 ml"},{"name":"Ajo","quantity":"1 diente"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Trocea y prepara judías blancas cocidas, merluza y zanahoria antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade judías blancas cocidas, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  35,
  'Media',
  array['Cocina casera', 'Legumbres']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  55,
  'Alubias con pollo y verduras',
  'Alubias con pollo y verduras: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pollo',
  '[{"name":"Alubias cocidas","quantity":"400 g"},{"name":"Pechuga de pollo","quantity":"300 g"},{"name":"Zanahoria","quantity":"1"},{"name":"Calabacín","quantity":"1"},{"name":"Caldo de pollo","quantity":"400 ml"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Trocea y prepara alubias cocidas, pechuga de pollo y zanahoria antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade alubias cocidas, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  40,
  'Media',
  array['Cocina casera', 'Legumbres']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  56,
  'Potaje rápido de garbanzos y bacalao',
  'Potaje rápido de garbanzos y bacalao: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pescado',
  '[{"name":"Garbanzos cocidos","quantity":"400 g"},{"name":"Bacalao desalado","quantity":"300 g"},{"name":"Espinacas","quantity":"200 g"},{"name":"Caldo de pescado","quantity":"350 ml"},{"name":"Pimentón","quantity":"1 cucharadita"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Trocea y prepara garbanzos cocidos, espinacas antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade garbanzos cocidos, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  35,
  'Media',
  array['Cocina casera', 'Legumbres']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  57,
  'Pollo guisado con zanahoria y patata',
  'Pollo guisado con zanahoria y patata: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pollo',
  '[{"name":"Muslos de pollo sin piel","quantity":"500 g"},{"name":"Patatas","quantity":"350 g"},{"name":"Zanahorias","quantity":"2"},{"name":"Caldo de pollo","quantity":"400 ml"},{"name":"Ajo","quantity":"2 dientes"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Trocea y prepara muslos de pollo sin piel, patatas y zanahorias antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade muslos de pollo sin piel, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  50,
  'Media',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  58,
  'Pollo en salsa de almendras',
  'Pollo en salsa de almendras: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pollo',
  '[{"name":"Pechuga de pollo","quantity":"350 g"},{"name":"Almendras naturales","quantity":"30 g"},{"name":"Cebolla","quantity":"0,5"},{"name":"Caldo de pollo","quantity":"300 ml"},{"name":"Ajo","quantity":"1 diente"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Trocea y prepara pechuga de pollo, almendras naturales y cebolla antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade pechuga de pollo, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  45,
  'Media',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  59,
  'Pollo mediterráneo con verduras',
  'Pollo mediterráneo con verduras: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pollo',
  '[{"name":"Pechuga de pollo","quantity":"350 g"},{"name":"Calabacín","quantity":"1"},{"name":"Berenjena","quantity":"1"},{"name":"Tomates cherry","quantity":"150 g"},{"name":"Aceite de oliva","quantity":"1 cucharada"},{"name":"Orégano","quantity":"1 cucharadita"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona calabacín y berenjena.","Coloca pechuga de pollo y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que pechuga de pollo alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  40,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  60,
  'Muslos de pollo al ajillo con patatas',
  'Muslos de pollo al ajillo con patatas: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pollo',
  '[{"name":"Muslos de pollo sin piel","quantity":"500 g"},{"name":"Patatas","quantity":"400 g"},{"name":"Ajo","quantity":"4 dientes"},{"name":"Limón","quantity":"1"},{"name":"Aceite de oliva","quantity":"1 cucharada"},{"name":"Perejil","quantity":"Al gusto"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona patatas y ajo.","Coloca muslos de pollo sin piel y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que muslos de pollo sin piel alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  50,
  'Media',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  61,
  'Pavo guisado con champiñones',
  'Pavo guisado con champiñones: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pollo',
  '[{"name":"Pavo en dados","quantity":"350 g"},{"name":"Champiñones","quantity":"250 g"},{"name":"Cebolla","quantity":"0,5"},{"name":"Caldo de pollo","quantity":"300 ml"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Trocea y prepara pavo en dados, champiñones y cebolla antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade pavo en dados, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  40,
  'Media',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  62,
  'Pavo al horno con boniato',
  'Pavo al horno con boniato: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pollo',
  '[{"name":"Filetes de pavo","quantity":"350 g"},{"name":"Boniato","quantity":"400 g"},{"name":"Calabacín","quantity":"1"},{"name":"Aceite de oliva","quantity":"1 cucharada"},{"name":"Pimentón","quantity":"1 cucharadita"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona boniato y calabacín.","Coloca filetes de pavo y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que filetes de pavo alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  40,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  63,
  'Tacos de pollo con aguacate',
  'Tacos de pollo con aguacate: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Wraps',
  '[{"name":"Pechuga de pollo","quantity":"300 g"},{"name":"Tortillas de maíz","quantity":"6"},{"name":"Aguacate","quantity":"1"},{"name":"Lechuga","quantity":"150 g"},{"name":"Lima","quantity":"1"},{"name":"Yogur natural","quantity":"1"}]'::jsonb,
  '["Prepara tortillas de maíz y aguacate y sazona pechuga de pollo.","Calienta bien una sartén o plancha con el aceite y cocina pechuga de pollo sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  25,
  'Fácil',
  array['Rápido']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  64,
  'Burrito de pollo, arroz y frijoles',
  'Burrito de pollo, arroz y frijoles: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Wraps',
  '[{"name":"Pechuga de pollo","quantity":"250 g"},{"name":"Tortillas integrales","quantity":"2 grandes"},{"name":"Arroz cocido","quantity":"160 g"},{"name":"Frijoles cocidos","quantity":"150 g"},{"name":"Lechuga","quantity":"100 g"},{"name":"Yogur natural","quantity":"1"}]'::jsonb,
  '["Prepara tortillas integrales y arroz cocido y sazona pechuga de pollo.","Calienta bien una sartén o plancha con el aceite y cocina pechuga de pollo sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  65,
  'Ternera guisada con patatas',
  'Ternera guisada con patatas: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Carne',
  '[{"name":"Ternera para guisar","quantity":"400 g"},{"name":"Patatas","quantity":"350 g"},{"name":"Zanahorias","quantity":"2"},{"name":"Caldo de carne","quantity":"500 ml"},{"name":"Cebolla","quantity":"0,5"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Trocea y prepara ternera para guisar, patatas y zanahorias antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade ternera para guisar, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  60,
  'Media',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  66,
  'Ternera con champiñones y arroz',
  'Ternera con champiñones y arroz: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Carne',
  '[{"name":"Ternera en tiras","quantity":"300 g"},{"name":"Champiñones","quantity":"250 g"},{"name":"Arroz","quantity":"150 g"},{"name":"Ajo","quantity":"1 diente"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Prepara champiñones y arroz y sazona ternera en tiras.","Calienta bien una sartén o plancha con el aceite y cocina ternera en tiras sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  67,
  'Solomillo de cerdo con boniato',
  'Solomillo de cerdo con boniato: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Carne',
  '[{"name":"Solomillo de cerdo","quantity":"400 g"},{"name":"Boniato","quantity":"400 g"},{"name":"Cebolla","quantity":"1"},{"name":"Aceite de oliva","quantity":"1 cucharada"},{"name":"Romero","quantity":"1 cucharadita"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona boniato y cebolla.","Coloca solomillo de cerdo y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que solomillo de cerdo alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  40,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  68,
  'Lomo de cerdo con verduras',
  'Lomo de cerdo con verduras: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Carne',
  '[{"name":"Filetes de lomo","quantity":"350 g"},{"name":"Calabacín","quantity":"1"},{"name":"Champiñones","quantity":"200 g"},{"name":"Arroz","quantity":"130 g"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Prepara calabacín y champiñones y sazona filetes de lomo.","Calienta bien una sartén o plancha con el aceite y cocina filetes de lomo sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  69,
  'Albóndigas de pavo en salsa',
  'Albóndigas de pavo en salsa: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Carne',
  '[{"name":"Carne picada de pavo","quantity":"400 g"},{"name":"Huevo","quantity":"1"},{"name":"Pan rallado","quantity":"30 g"},{"name":"Tomate triturado","quantity":"300 g"},{"name":"Zanahoria","quantity":"1"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Trocea y prepara carne picada de pavo, huevo y pan rallado antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade carne picada de pavo, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  45,
  'Media',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  70,
  'Pastel de carne y patata',
  'Pastel de carne y patata: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Carne',
  '[{"name":"Carne picada de ternera","quantity":"350 g"},{"name":"Patatas","quantity":"500 g"},{"name":"Zanahoria","quantity":"1"},{"name":"Tomate triturado","quantity":"150 g"},{"name":"Queso rallado","quantity":"50 g"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona patatas y zanahoria.","Coloca carne picada de ternera y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que carne picada de ternera alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  55,
  'Media',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  71,
  'Dorada al horno con patatas',
  'Dorada al horno con patatas: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pescado',
  '[{"name":"Doradas limpias","quantity":"2"},{"name":"Patatas","quantity":"400 g"},{"name":"Cebolla","quantity":"1"},{"name":"Limón","quantity":"1"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona patatas y cebolla.","Coloca doradas limpias y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que doradas limpias alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  40,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  72,
  'Lubina al limón con verduras',
  'Lubina al limón con verduras: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pescado',
  '[{"name":"Lubinas limpias","quantity":"2"},{"name":"Calabacín","quantity":"1"},{"name":"Zanahorias","quantity":"2"},{"name":"Limón","quantity":"1"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona calabacín y zanahorias.","Coloca lubinas limpias y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que lubinas limpias alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  35,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  73,
  'Bacalao con tomate y patata',
  'Bacalao con tomate y patata: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pescado',
  '[{"name":"Lomos de bacalao","quantity":"350 g"},{"name":"Tomate triturado","quantity":"300 g"},{"name":"Patatas","quantity":"300 g"},{"name":"Cebolla","quantity":"0,5"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Trocea y prepara lomos de bacalao, tomate triturado y patatas antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade lomos de bacalao, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  40,
  'Media',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  74,
  'Merluza en salsa verde con guisantes',
  'Merluza en salsa verde con guisantes: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pescado',
  '[{"name":"Lomos de merluza","quantity":"350 g"},{"name":"Guisantes","quantity":"180 g"},{"name":"Caldo de pescado","quantity":"250 ml"},{"name":"Ajo","quantity":"2 dientes"},{"name":"Perejil","quantity":"Al gusto"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Trocea y prepara lomos de merluza, guisantes y ajo antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade lomos de merluza, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  30,
  'Media',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  75,
  'Salmón con boniato en airfryer',
  'Salmón con boniato en airfryer: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pescado',
  '[{"name":"Lomos de salmón","quantity":"2"},{"name":"Boniato","quantity":"400 g"},{"name":"Limón","quantity":"1"},{"name":"Aceite de oliva","quantity":"1 cucharada"},{"name":"Eneldo","quantity":"Al gusto"}]'::jsonb,
  '["Precalienta la airfryer a 190 °C y prepara boniato con el aliño indicado.","Coloca boniato en una sola capa, sin amontonar, y pulveriza o reparte el aceite medido.","Cocina hasta que quede dorado, dando la vuelta o agitando la cesta a mitad del tiempo.","Comprueba que el interior esté bien cocinado y sirve con la guarnición."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera', 'Omega 3']::text[],
  true,
  true,
  true,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  76,
  'Atún encebollado con arroz',
  'Atún encebollado con arroz: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pescado',
  '[{"name":"Atún fresco en dados","quantity":"350 g"},{"name":"Cebollas","quantity":"2"},{"name":"Arroz","quantity":"140 g"},{"name":"Caldo de pescado","quantity":"200 ml"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Trocea y prepara atún fresco en dados, cebollas y arroz antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade atún fresco en dados, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  35,
  'Media',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  77,
  'Calamares salteados con arroz',
  'Calamares salteados con arroz: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pescado',
  '[{"name":"Calamares limpios","quantity":"400 g"},{"name":"Arroz","quantity":"150 g"},{"name":"Ajo","quantity":"2 dientes"},{"name":"Perejil","quantity":"Al gusto"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Prepara arroz y ajo y sazona calamares limpios.","Calienta bien una sartén o plancha con el aceite y cocina calamares limpios sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  78,
  'Brochetas de gambas y verduras',
  'Brochetas de gambas y verduras: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pescado',
  '[{"name":"Gambas peladas","quantity":"350 g"},{"name":"Calabacín","quantity":"1"},{"name":"Pimiento rojo","quantity":"1"},{"name":"Arroz","quantity":"130 g"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Prepara calabacín y pimiento rojo y sazona gambas peladas.","Calienta bien una sartén o plancha con el aceite y cocina gambas peladas sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  25,
  'Fácil',
  array['Rápido']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  79,
  'Pasta integral con atún y verduras',
  'Pasta integral con atún y verduras: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pasta',
  '[{"name":"Pasta integral","quantity":"170 g"},{"name":"Atún al natural","quantity":"2 latas"},{"name":"Calabacín","quantity":"1"},{"name":"Tomate triturado","quantity":"200 g"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Cuece la pasta en agua con sal hasta dejarla al dente y reserva un poco del agua de cocción.","Mientras, cocina pasta integral con atún al natural y calabacín en una sartén amplia.","Añade la pasta escurrida, mezcla con la salsa y usa un poco del agua reservada si necesita quedar más jugosa.","Cocina todo junto un minuto y sirve recién hecho."]'::jsonb,
  25,
  'Fácil',
  array['Rápido']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  80,
  'Pasta boloñesa de lentejas',
  'Pasta boloñesa de lentejas: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pasta',
  '[{"name":"Pasta","quantity":"170 g"},{"name":"Lentejas cocidas","quantity":"300 g"},{"name":"Tomate triturado","quantity":"300 g"},{"name":"Zanahoria","quantity":"1"},{"name":"Cebolla","quantity":"0,5"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Cuece la pasta en agua con sal hasta dejarla al dente y reserva un poco del agua de cocción.","Mientras, cocina pasta con lentejas cocidas y tomate triturado en una sartén amplia.","Añade la pasta escurrida, mezcla con la salsa y usa un poco del agua reservada si necesita quedar más jugosa.","Cocina todo junto un minuto y sirve recién hecho."]'::jsonb,
  35,
  'Fácil',
  array['Cocina casera', 'Legumbres']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  81,
  'Macarrones con pollo y espinacas',
  'Macarrones con pollo y espinacas: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pasta',
  '[{"name":"Macarrones","quantity":"170 g"},{"name":"Pechuga de pollo","quantity":"250 g"},{"name":"Espinacas","quantity":"200 g"},{"name":"Leche evaporada","quantity":"120 ml"},{"name":"Aceite de oliva","quantity":"1 cucharadita"}]'::jsonb,
  '["Cuece la pasta en agua con sal hasta dejarla al dente y reserva un poco del agua de cocción.","Mientras, cocina macarrones con pechuga de pollo y espinacas en una sartén amplia.","Añade la pasta escurrida, mezcla con la salsa y usa un poco del agua reservada si necesita quedar más jugosa.","Cocina todo junto un minuto y sirve recién hecho."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  82,
  'Espaguetis con gambas y calabacín',
  'Espaguetis con gambas y calabacín: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pasta',
  '[{"name":"Espaguetis","quantity":"170 g"},{"name":"Gambas peladas","quantity":"250 g"},{"name":"Calabacín","quantity":"1"},{"name":"Ajo","quantity":"2 dientes"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Cuece la pasta en agua con sal hasta dejarla al dente y reserva un poco del agua de cocción.","Mientras, cocina espaguetis con gambas peladas y calabacín en una sartén amplia.","Añade la pasta escurrida, mezcla con la salsa y usa un poco del agua reservada si necesita quedar más jugosa.","Cocina todo junto un minuto y sirve recién hecho."]'::jsonb,
  25,
  'Fácil',
  array['Rápido']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  83,
  'Cuscús con pollo y verduras',
  'Cuscús con pollo y verduras: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Arroz',
  '[{"name":"Cuscús","quantity":"160 g"},{"name":"Pechuga de pollo","quantity":"300 g"},{"name":"Calabacín","quantity":"1"},{"name":"Zanahoria","quantity":"1"},{"name":"Caldo de pollo","quantity":"180 ml"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Prepara pechuga de pollo y calabacín y sazona cuscús.","Calienta bien una sartén o plancha con el aceite y cocina cuscús sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  84,
  'Quinoa con salmón y aguacate',
  'Quinoa con salmón y aguacate: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Arroz',
  '[{"name":"Quinoa","quantity":"150 g"},{"name":"Salmón","quantity":"250 g"},{"name":"Aguacate","quantity":"1"},{"name":"Zanahoria","quantity":"1"},{"name":"Limón","quantity":"1"},{"name":"Aceite de oliva","quantity":"1 cucharadita"}]'::jsonb,
  '["Lava, seca y corta aguacate y zanahoria.","Prepara quinoa y deja que se temple antes de mezclarlo si se ha cocinado.","Combina los ingredientes en un bol amplio y prepara el aliño por separado.","Aliña justo antes de servir, mezcla bien y ajusta el punto de sal."]'::jsonb,
  25,
  'Fácil',
  array['Rápido']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  85,
  'Arroz meloso con pollo y verduras',
  'Arroz meloso con pollo y verduras: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Arroz',
  '[{"name":"Arroz","quantity":"170 g"},{"name":"Pollo troceado","quantity":"350 g"},{"name":"Calabacín","quantity":"1"},{"name":"Zanahoria","quantity":"1"},{"name":"Caldo de pollo","quantity":"600 ml"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Trocea y sazona arroz; prepara también pollo troceado y calabacín.","Rehoga la proteína y las verduras con el aceite hasta que empiecen a dorarse.","Incorpora el arroz, mezcla durante un minuto y añade el caldo caliente.","Cuece sin remover en exceso hasta que el arroz esté en su punto y déjalo reposar 5 minutos."]'::jsonb,
  40,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  86,
  'Arroz con bacalao y espinacas',
  'Arroz con bacalao y espinacas: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Arroz',
  '[{"name":"Arroz","quantity":"170 g"},{"name":"Bacalao desalado","quantity":"300 g"},{"name":"Espinacas","quantity":"180 g"},{"name":"Caldo de pescado","quantity":"500 ml"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Trocea y sazona arroz; prepara también espinacas.","Rehoga la proteína y las verduras con el aceite hasta que empiecen a dorarse.","Incorpora el arroz, mezcla durante un minuto y añade el caldo caliente.","Cuece sin remover en exceso hasta que el arroz esté en su punto y déjalo reposar 5 minutos."]'::jsonb,
  40,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  87,
  'Tortilla de calabacín con ensalada',
  'Tortilla de calabacín con ensalada: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Huevos',
  '[{"name":"Huevos","quantity":"5"},{"name":"Calabacín","quantity":"1"},{"name":"Lechuga","quantity":"150 g"},{"name":"Zanahoria","quantity":"1"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Prepara calabacín y lechuga y sazona huevos.","Calienta bien una sartén o plancha con el aceite y cocina huevos sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  25,
  'Fácil',
  array['Rápido']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  88,
  'Huevos al plato con verduras',
  'Huevos al plato con verduras: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Huevos',
  '[{"name":"Huevos","quantity":"4"},{"name":"Tomate triturado","quantity":"250 g"},{"name":"Calabacín","quantity":"1"},{"name":"Guisantes","quantity":"120 g"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona tomate triturado y calabacín.","Coloca huevos y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que huevos alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  89,
  'Shakshuka suave con garbanzos',
  'Shakshuka suave con garbanzos: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Huevos',
  '[{"name":"Huevos","quantity":"4"},{"name":"Garbanzos cocidos","quantity":"250 g"},{"name":"Tomate triturado","quantity":"350 g"},{"name":"Pimiento rojo","quantity":"0,5"},{"name":"Cebolla","quantity":"0,5"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Trocea y prepara huevos, garbanzos cocidos y tomate triturado antes de empezar.","Sofríe primero los ingredientes aromáticos con el aceite hasta que comiencen a ablandarse.","Añade huevos, rehoga para que tome color y cubre con el líquido indicado.","Cocina a fuego suave hasta que esté tierno, remueve de vez en cuando y rectifica de sal antes de servir."]'::jsonb,
  30,
  'Media',
  array['Cocina casera', 'Legumbres']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  90,
  'Revuelto de pollo, champiñones y patata',
  'Revuelto de pollo, champiñones y patata: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Huevos',
  '[{"name":"Huevos","quantity":"4"},{"name":"Pechuga de pollo","quantity":"200 g"},{"name":"Champiñones","quantity":"200 g"},{"name":"Patatas","quantity":"300 g"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Prepara pechuga de pollo y champiñones y sazona huevos.","Calienta bien una sartén o plancha con el aceite y cocina huevos sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  91,
  'Ensalada completa de salmón y patata',
  'Ensalada completa de salmón y patata: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Ligero',
  '[{"name":"Salmón","quantity":"250 g"},{"name":"Patatas","quantity":"350 g"},{"name":"Huevos","quantity":"2"},{"name":"Lechuga","quantity":"150 g"},{"name":"Zanahoria","quantity":"1"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Lava, seca y corta huevos y lechuga.","Prepara patatas y deja que se temple antes de mezclarlo si se ha cocinado.","Combina los ingredientes en un bol amplio y prepara el aliño por separado.","Aliña justo antes de servir, mezcla bien y ajusta el punto de sal."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  92,
  'Ensalada de pasta, pollo y huevo',
  'Ensalada de pasta, pollo y huevo: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Ligero',
  '[{"name":"Pasta","quantity":"160 g"},{"name":"Pechuga de pollo","quantity":"250 g"},{"name":"Huevos","quantity":"2"},{"name":"Lechuga","quantity":"120 g"},{"name":"Zanahoria","quantity":"1"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Lava, seca y corta pechuga de pollo y huevos.","Prepara pasta y deja que se temple antes de mezclarlo si se ha cocinado.","Combina los ingredientes en un bol amplio y prepara el aliño por separado.","Aliña justo antes de servir, mezcla bien y ajusta el punto de sal."]'::jsonb,
  25,
  'Fácil',
  array['Rápido']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  93,
  'Bowl de arroz, atún y aguacate',
  'Bowl de arroz, atún y aguacate: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Ligero',
  '[{"name":"Arroz cocido","quantity":"160 g"},{"name":"Atún al natural","quantity":"2 latas"},{"name":"Aguacate","quantity":"1"},{"name":"Huevos","quantity":"2"},{"name":"Zanahoria","quantity":"1"},{"name":"Limón","quantity":"1"}]'::jsonb,
  '["Lava, seca y corta atún al natural y aguacate.","Prepara arroz cocido y deja que se temple antes de mezclarlo si se ha cocinado.","Combina los ingredientes en un bol amplio y prepara el aliño por separado.","Aliña justo antes de servir, mezcla bien y ajusta el punto de sal."]'::jsonb,
  20,
  'Fácil',
  array['Rápido']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  94,
  'Bowl de pollo, quinoa y verduras',
  'Bowl de pollo, quinoa y verduras: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Ligero',
  '[{"name":"Pechuga de pollo","quantity":"300 g"},{"name":"Quinoa","quantity":"150 g"},{"name":"Calabacín","quantity":"1"},{"name":"Zanahoria","quantity":"1"},{"name":"Aguacate","quantity":"0,5"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Prepara quinoa y calabacín y sazona pechuga de pollo.","Calienta bien una sartén o plancha con el aceite y cocina pechuga de pollo sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  30,
  'Fácil',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  95,
  'Pizza integral de verduras y pollo',
  'Pizza integral de verduras y pollo: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Caprichos',
  '[{"name":"Base integral de pizza","quantity":"1"},{"name":"Pechuga de pollo","quantity":"220 g"},{"name":"Tomate triturado","quantity":"120 g"},{"name":"Calabacín","quantity":"0,5"},{"name":"Queso mozzarella","quantity":"80 g"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona pechuga de pollo y tomate triturado.","Coloca base integral de pizza y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que base integral de pizza alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  35,
  'Fácil',
  array['Cocina casera', 'Fin de semana']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  96,
  'Hamburguesa de salmón con patatas',
  'Hamburguesa de salmón con patatas: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Caprichos',
  '[{"name":"Salmón picado","quantity":"350 g"},{"name":"Pan de hamburguesa","quantity":"2"},{"name":"Huevo","quantity":"1"},{"name":"Lechuga","quantity":"100 g"},{"name":"Patatas","quantity":"350 g"},{"name":"Aceite de oliva","quantity":"1 cucharada"}]'::jsonb,
  '["Prepara huevo y lechuga y sazona pan de hamburguesa.","Calienta bien una sartén o plancha con el aceite y cocina pan de hamburguesa sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  35,
  'Fácil',
  array['Cocina casera', 'Fin de semana']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  97,
  'Piadina de pollo y verduras',
  'Piadina de pollo y verduras: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Wraps',
  '[{"name":"Piadinas","quantity":"2"},{"name":"Pechuga de pollo","quantity":"280 g"},{"name":"Calabacín","quantity":"1"},{"name":"Queso mozzarella","quantity":"60 g"},{"name":"Lechuga","quantity":"100 g"}]'::jsonb,
  '["Prepara pechuga de pollo y calabacín y sazona piadinas.","Calienta bien una sartén o plancha con el aceite y cocina piadinas sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  25,
  'Fácil',
  array['Rápido']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  98,
  'Quesadillas de pollo y frijoles',
  'Quesadillas de pollo y frijoles: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Wraps',
  '[{"name":"Tortillas de trigo","quantity":"4"},{"name":"Pechuga de pollo","quantity":"250 g"},{"name":"Frijoles cocidos","quantity":"180 g"},{"name":"Queso rallado","quantity":"70 g"},{"name":"Lechuga","quantity":"100 g"}]'::jsonb,
  '["Prepara pechuga de pollo y frijoles cocidos y sazona tortillas de trigo.","Calienta bien una sartén o plancha con el aceite y cocina tortillas de trigo sin moverlo hasta que se dore.","Da la vuelta, termina la cocción a fuego medio y prepara mientras la guarnición indicada.","Sirve recién hecho y ajusta el aliño al gusto."]'::jsonb,
  25,
  'Fácil',
  array['Rápido']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  99,
  'Canelones de carne y verduras',
  'Canelones de carne y verduras: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pasta',
  '[{"name":"Placas de canelones","quantity":"12"},{"name":"Carne picada de ternera","quantity":"350 g"},{"name":"Calabacín","quantity":"1"},{"name":"Tomate triturado","quantity":"250 g"},{"name":"Bechamel ligera","quantity":"250 ml"},{"name":"Queso rallado","quantity":"60 g"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona carne picada de ternera y calabacín.","Coloca placas de canelones y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que placas de canelones alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  55,
  'Media',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
),
(
  100,
  'Lasaña de pollo y verduras',
  'Lasaña de pollo y verduras: una opción variada y completa para la comida principal del día.',
  'main_fasting',
  'Pasta',
  '[{"name":"Placas de lasaña","quantity":"8"},{"name":"Pechuga de pollo picada","quantity":"350 g"},{"name":"Calabacín","quantity":"1"},{"name":"Zanahoria","quantity":"1"},{"name":"Bechamel ligera","quantity":"250 ml"},{"name":"Queso rallado","quantity":"60 g"}]'::jsonb,
  '["Precalienta el horno a 200 °C. Limpia, corta y sazona pechuga de pollo picada y calabacín.","Coloca placas de lasaña y el resto de ingredientes en una fuente, añade el aceite medido y mezcla para repartir el aliño.","Hornea hasta que placas de lasaña alcance el punto adecuado y la guarnición esté tierna, removiendo o dando la vuelta a mitad de cocción.","Deja reposar 3 minutos, comprueba el punto y sirve."]'::jsonb,
  55,
  'Media',
  array['Cocina casera']::text[],
  true,
  true,
  false,
  'Cantidades orientativas para dos adultos; ajusta la guarnición a vuestro apetito.'
)
on conflict (id) do update set
  name = excluded.name,
  description = excluded.description,
  collection = excluded.collection,
  category = excluded.category,
  ingredients = excluded.ingredients,
  instructions = excluded.instructions,
  cooking_time = excluded.cooking_time,
  difficulty = excluded.difficulty,
  tags = excluded.tags,
  protein = excluded.protein,
  healthy = excluded.healthy,
  air_fryer = excluded.air_fryer,
  notes = excluded.notes,
  updated_at = now()
where public.meals.household_id is null;

commit;
